### DISCUSSION TITLE
Is the sensor name that triggered the alarm available?

### DISCUSSION THREAD

**Discussion by jcallaghan** [tsightler/ring-mqtt#296] [Support Q&A] [answered]
@tsightler firstly thank you (and all the other contributors) for your hard work maintaining this project! 🙏🏼

Whilst out on a dog walk this evening our alarm triggered. My automation kicked in and I got a critical notification where I was able to silence the alarm (having only just left) and reset it. This got me thinking, while my notification worked perfectly, I wondered if there was any way to get the device/sensor that triggered the alarm to add more detail to the notification?

Having done a little homework since getting back from my dog walk I wasn't able to spot anything. The closes thing I found was your message in issue #27. This is helpful in determining the burglar-alarm was the cause for the alarm but I wondered if the sensor that caused the alarm was available? 

> For example, related to this feature request for alarm status the standard Alarm Control Panel now has support for "pending" (entry-delay) and "triggered" (any active alarm) state which you can use for simple automations. However, if you want more detail on the type of alarm the new "info" sensor includes the detailed alarmState attribute which can have the following values:
> 
> burglar-alarm
> entry-delay
> fire-alarm
> co-alarm
> panic
> user-verified-burglar-alarm
> user-verified-co-or-fire-alarm
> burglar-accelerated-alarm

**Comment by tsightler** [comment, marked as answer]
I don't think that information is available within the API that I know of, although it might be.  Does this show in the Ring app?  I'm guessing it's in the event history, but is it anywhere else in the app?  I think you could probably just include the state of all sensors in your notification, but I'll admit I haven't played with the HA notifications very much.

**Comment by arallsopp** [comment]
I use an automation akin to the below in concert with the alarm trigger (sensitive info removed)

```
alias: Alert on Change of Exterior Door
description: ''
trigger:
  - platform: state
    entity_id:
      - binary_sensor.office_garden_door
      - binary_sensor.utility_to_patio_door
      - binary_sensor.atrium_bi_folds
      - binary_sensor.front_door
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.alert_on_change_external_door_status
    state: 'on'
action:
  - service: notify.mobile_app_iphone_2
    data:
      message: '{{ trigger.to_state.attributes.friendly_name }} has been opened'
      title: EXTERIOR DOOR OPENED
mode: single
```

This will send my phone a message saying which alarm component was triggered. I know it doesn't give the alarm context, but it is a handy way to see why the alarm has been raised and I can generally work it out from there. 

Perhaps you can just add the info state as the message title?
