### DISCUSSION TITLE
Errors with snapshot config

### DISCUSSION THREAD

**Discussion by lyndoncox** [tsightler/ring-mqtt#317] [Support Q&A] [answered]
Firstly, THANK YOU! This addon is incredibly awesome. Thank you for the time and effort put into developing this.

I'm having an issue with the snapshot piece. I know it's something I've configured wrong, but I'm stumped as to the cause. I'm getting these errors in my logs:

```
ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering 'http://192.168.1.72:8123{{ states.camera.front_door_snapshot.attributes.entity_picture }}'
ERROR (MainThread) [homeassistant.components.generic.camera] Error parsing template Template("http://192.168.1.72:8123{{ states.camera.front_door_snapshot.attributes.entity_picture }}"): UndefinedError: 'None' has no attribute 'attributes'
```
Here's what I have in configuration.yaml

```
camera:
  - platform: generic
    name: Back Door Video
    still_image_url: http://192.168.1.72:8123{{ states.camera.back_door_snapshot.attributes.entity_picture }}
    stream_source: rtsp://****:*****@03cabcc9-ring-mqtt:8554/34151343d928_live
    verify_ssl: false
  - platform: generic
    name: Front Door Video    
    still_image_url: http://192.168.1.72:8123{{ states.camera.front_door_snapshot.attributes.entity_picture }}
    stream_source: rtsp://****:****@03cabcc9-ring-mqtt:8554/94e36d6d73b9_live
    verify_ssl: false
```

Any idea what I have wrong here?

Thanks in advance!
