### DISCUSSION TITLE
Unable to start docker ring-mqtt fails with "ring-mqtt Unable to connect to MQTT broker connect ECONNREFUSED 127.0.0.1:1883"

### DISCUSSION THREAD

**Discussion by mwatz1234** [tsightler/ring-mqtt#378] [Support Q&A] [answered]
First time trying to setup ring-mqtt.  
I have mqtt setup with mosquitto and home assistant mqtt plugin was setup to to the mqtt.  
Since HA is able to be configured to talk the mqtt I belive the permissions is working (not sure if only 1 instance of a user could talk to mqtt at a time)

This is the error message I am getting is below.  I am not sure if it thinks the username/password is word, or something else is not configured correctly.

  ring-mqtt  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
  ring-mqtt  | [s6-init] ensuring user provided files have correct perms...exited 0.
  ring-mqtt  | [fix-attrs.d] applying ownership & permissions fixes...
  ring-mqtt  | [fix-attrs.d] done.
  ring-mqtt  | [cont-init.d] executing container initialization scripts...
  ring-mqtt  | [cont-init.d] ring-mqtt.sh: executing...
  ring-mqtt  | -------------------------------------------------------
  ring-mqtt  | | Ring-MQTT with Video Streaming                      |
  ring-mqtt  | | Docker Edition                                      |
  ring-mqtt  | |                                                     |
  ring-mqtt  | | Report issues at:                                   |
  ring-mqtt  | | https://github.com/tsightler/ring-mqtt              |
  ring-mqtt  | -------------------------------------------------------
  ring-mqtt  | [cont-init.d] ring-mqtt.sh: exited 0.
  ring-mqtt  | [cont-init.d] done.
  ring-mqtt  | [services.d] starting services
  ring-mqtt  | [services.d] done.
  ring-mqtt  | -------------------------------------------------------
  ring-mqtt  | ring-mqtt.js version: 5.0.1
  ring-mqtt  | Node version v16.14.2
  ring-mqtt  | NPM version 8.1.3
  ring-mqtt  | git version 2.34.2
  ring-mqtt  | -------------------------------------------------------
  ring-mqtt  | Running ring-mqtt...
  ring-mqtt  | 2022-05-22T19:16:08.069Z ring-mqtt Detected runmode: docker
  ring-mqtt  | 2022-05-22T19:16:08.074Z ring-mqtt Configuration file: /data/config.json
  ring-mqtt  | 2022-05-22T19:16:08.078Z ring-mqtt MQTT URL: mqtt://mosquitto:********@localhost:1883
  ring-mqtt  | 2022-05-22T19:16:11.558Z ring-mqtt Reading latest data from state file: /data/ring-state.json
  ring-mqtt  | 2022-05-22T19:16:11.722Z ring-mqtt Attempting connection to Ring API using saved refresh token...
  ring-mqtt  | 2022-05-22T19:16:12.486Z ring-mqtt Successfully established connection to Ring API using saved token
  ring-mqtt  | 2022-05-22T19:16:13.676Z ring-mqtt Successfully saved updated state file: /data/ring-state.json
  ring-mqtt  | 2022-05-22T19:16:14.486Z ring-mqtt Attempting connection to MQTT broker...
  **ring-mqtt  | 2022-05-22T19:16:14.641Z ring-mqtt Unable to connect to MQTT broker connect ECONNREFUSED 127.0.0.1:1883**
  ring-mqtt  | 2022-05-22T19:16:15.727Z ring-mqtt Attempting to reconnect to MQTT broker...

my docker-compose is setup with
```  
version: '3.2'
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/pi/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - mosquitto
  mosquitto:
    container_name: mosquitto
    image: "eclipse-mosquitto:latest"
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/pi/mosquitto/config:/mosquitto/config:rw
      - /home/pi/mosquitto/log:/mosquitto/log
      - /home/pi/mosquitto/data/:/mosquitto/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  ring-mqtt:
    container_name: ring-mqtt
    image: tsightler/ring-mqtt:latest
    restart: "no"
    ports:
      - 8554:8554                      # Enable RTSP port for external media player access
    volumes:
      - /home/pi/ring-mqtt/data:/data           # Mapping of local folder to provide persistent storage
    logging:                           #limit logs to 10m and 3 files
      options:
        max-size: 10m
        max-file: "3"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

ring-mqtt config.json is setup as:
```
{
    "mqtt_url": "mqtt://username:password@localhost:1883",
    "mqtt_options": "",
    "livestream_user": "",
    "livestream_pass": "",
    "disarm_code": "",
    "enable_cameras": false,
    "enable_modes": false,
    "enable_panic": false,
    "hass_topic": "homeassistant/status",
    "ring_topic": "ring",
    "location_ids": [
        ""
    ]
}
```
the mosquitto.conf file is setup like:
```
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

listener 1883
## Authentication ##
allow_anonymous false
password_file /mosquitto/config/credentials
```
