### DISCUSSION TITLE
Example Home Assistant dashboards?

### DISCUSSION THREAD

**Discussion by ankushg** [tsightler/ring-mqtt#485] [General Discussion]
Does anyone have good-looking dashboards for the entities exposed by ring-mqtt?

 I'm having a difficult time putting together some sort of automatically generated dashboard because:
- I have around 20 sensor, and
- each Ring device exposes multiple entities, and 
- each type of device has slightly _different_ entities: 
  - most have a primary sensor entity that is either a regular sensor or binary_sensor
  - most have a `tamper` entity
  - some have a `bypass_mode` entity 
  - some have a `battery` entity
  - some have a `volume` entity

I'm hoping there's a way to somehow automatically/programatically generate a nice dashboard view for all ring-mqtt devices in Lovelace, but drawing a blank on how to do it 😕

**Comment by tsightler** [comment]
I definitely am not aware of any way to do it programmatically, but then again, I'm not much of a UI guy and mostly just use HA for automations, I rarely actually look at the HA UI itself.

That being said, I manually created this dashboard long ago using a combination of layout-card, vertical-stack and multi-entity-row cards and, while it's not really special in any way, it packs a lot of data in a small amount of space and lets me see the complete status of my alarm and camera sensors in a compact amount of space, even on my mobile device it's only about 1.5 screens long.  I don't bother with the tamper and battery stuff on the individual sensors in the UI because those will alert anyway.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/17784731/196262791-8dd24b01-a812-438d-bddb-85c3ae8c98fc.png">

**Reply by ankushg** [reply]
Thanks for the detail! Any chance you could share the yaml for that?

**Reply by tsightler** [reply]
I'm not sure how useful it is since all the entity names would be different, but here you go.  I'm sure there are way nicer ways to present this but I just wanted to get all the sensors and locks in as small of an area as possible and this has really worked well for me for that occassion where I do want to see the status of all sensors at a glance.  I have mulitiple views for environmental (HVAC, fireplace, weather, humidity monitoring, etc), lights/fans, security system (the one posted here), cameras (snapshot view with click to view live and event stremas, light controls as well as motion status), and irrigation monitoring (zone run times, gallons used vs saved, future run times, soil moisture, etc).

I know a lot of people like fancy layouts with floorplans and room images and all kinds of stuff like that but I find those don't really work well on mobile devices which seems to be my primary use case.  Instead I prefer the ability to check the status of everything at a super quick glance when I'm away, so I try to make condensed layouts where each view fits on one screen on my phone with minimal scrolling required, a few taps and I can see everything.

```
cards:
  - cards:
      - cards:
          - entity: alarm_control_panel.sightler_acres_alarm
            type: alarm-panel
          - entities:
              - type: section
              - entities:
                  - entity: switch.sightler_acres_panic_police
                    name: Burglar
                  - entity: switch.sightler_acres_panic_fire
                    name: Fire
                  - attribute: tamperStatus
                    name: Tamper
                entity: sensor.sightler_acres_alarm_info
                icon: mdi:bell
                name: Alarm Status
                secondary_info:
                  attribute: alarmState
                show_state: false
                type: custom:multiple-entity-row
              - entities:
                  - attribute: batteryStatus
                    name: Battery
                  - attribute: acStatus
                    name: AC Power
                  - attribute: tamperStatus
                    name: Tamper
                entity: sensor.sightler_acres_base_station_info
                icon: mdi:security
                name: Base Station
                secondary_info:
                  attribute: commStatus
                show_state: false
                type: custom:multiple-entity-row
              - entities:
                  - attribute: batteryLevel
                    name: Battery
                    unit: '%'
                  - attribute: tamperStatus
                    name: Tamper
                entity: sensor.entry_keypad_info
                icon: mdi:dialpad
                name: Entry Keypad
                secondary_info:
                  attribute: commStatus
                show_state: false
                type: custom:multiple-entity-row
              - type: section
              - entities:
                  - icon: mdi:police-badge
                    name: Call Police
                    state_color: true
                    tap_action:
                      action: toggle
                      confirmation: Trigger Police Panic Now?
                  - icon: mdi:fire
                    name: Call Fire
                    state_color: true
                    tap_action:
                      action: toggle
                      confirmation: Trigger Fire Panic Now?
                entity: switch.sightler_acres_panic_police
                icon: mdi:alarm-light
                name: Panic Buttons
                show_state: false
                type: custom:multiple-entity-row
              - type: section
              - entities:
                  - entity: lock.kwikset_smartcode_deadbolt_5_1f4506fd_door_lock
                    name: Pool House
                    state_color: true
                entity: lock.kwikset_smartcode_deadbolt_5_1f4506fd_door_lock
                type: custom:multiple-entity-row
                name: Door Locks
                show_state: false
                state_color: true
            type: entities
        type: vertical-stack
    type: custom:stack-in-card
  - entities:
      - entities:
          - entity: binary_sensor.front_entry_door
            name: Front
          - entity: binary_sensor.rear_entry_door
            name: Rear
          - entity: binary_sensor.garage_entry_door
            name: Garage
        entity: group.all_entry_door_sensors
        icon: mdi:door
        name: Entry Doors
        secondary_info: last-changed
        show_state: false
        state_color: true
        type: custom:multiple-entity-row
      - entities:
          - entity: binary_sensor.garage_double_car_door
            name: Double
          - entity: binary_sensor.garage_single_car_door
            name: Single
          - entity: binary_sensor.garage_man_door
            name: Man
        entity: group.external_garage_door_sensors
        icon: mdi:garage-variant
        name: Garage Doors
        secondary_info: last-changed
        show_state: false
        state_color: true
        type: custom:multiple-entity-row
      - entities:
          - entity: binary_sensor.living_room_motion
            name: Living Room
          - entity: binary_sensor.screen_porch_motion
            name: Screen Porch
        entity: group.alarm_motion_sensors
        icon: mdi:motion-sensor
        name: Alarm Motion
        secondary_info: last-changed
        show_state: false
        state_color: true
        type: custom:multiple-entity-row
      - entities:
          - entity: binary_sensor.front_garage_side_motion
            name: Garage Side
          - entity: binary_sensor.front_bedroom_side_motion
            name: Bedroom Side
        entity: group.front_yard_motion_sensors
        icon: mdi:motion-sensor
        name: Front Yard Motion
        secondary_info: last-changed
        show_state: false
        state_color: true
        type: custom:multiple-entity-row
      - entities:
          - entity: binary_sensor.front_porch_motion
            name: Front
          - entity: binary_sensor.screen_porch_motion_camera
            name: Screen
        entity: group.porch_sensors
        icon: mdi:motion-sensor
        name: Porch Motion
        secondary_info: last-changed
        show_state: false
        state_color: true
        type: custom:multiple-entity-row
      - entities:
          - entity: binary_sensor.front_doorbell_ding
            name: Ding
          - entity: binary_sensor.front_doorbell_motion
            name: Motion
        entity: group.doorbell_sensors
        icon: mdi:doorbell
        name: Front Doorbell
        secondary_info: last-changed
        show_state: false
        state_color: true
        type: custom:multiple-entity-row
      - entities:
          - entity: binary_sensor.guest_hall_listener_smoke
            name: Smoke
          - entity: binary_sensor.guest_hall_listener_co
            name: CO
        entity: group.guest_hall_smoke_co
        icon: mdi:smoke-detector
        name: Guest Hall Smoke/CO
        show_state: false
        state_color: true
        type: custom:multiple-entity-row
      - entities:
          - entity: binary_sensor.bonus_room_smoke
            name: Smoke
          - entity: binary_sensor.bonus_room_co
            name: CO
        entity: group.bonus_room_smoke_co
        icon: mdi:smoke-detector
        name: Bonus Room Smoke/CO
        show_state: false
        state_color: true
        type: custom:multiple-entity-row
      - entities:
          - entity: binary_sensor.laundry_flood_flood
            name: Laundry
          - entity: binary_sensor.water_heater_flood
            name: Water Heater
        entity: group.flood_sensors
        icon: mdi:home-flood
        name: Flood Sensors
        show_state: false
        state_color: true
        type: custom:multiple-entity-row
    show_header_toggle: false
    type: entities
type: custom:layout-card
```
