### DISCUSSION TITLE
Errors when deploying ring-mqtt docker container

### DISCUSSION THREAD

**Discussion by d0dge** [tsightler/ring-mqtt#559] [Support Q&A] [answered]
I'm trying to set up ring-mqtt in a Docker container on my Firewalla Gold box.  Full disclosure - I am relatively new to Docker, but I already have Home Assistant and my MQTT broker up and running and working fine.  However when trying to run ring-mqtt via docker-compose, I get the following when I run `journalctl -xe`:

`Feb 14 05:50:05 firewalla systemd[1]: Starting ring-mqtt service with docker compose...`
`Feb 14 05:50:05 firewalla systemd[24776]: docker-compose@ring-mqtt.service: Changing to the requested working directory failed: No such file or directory`
`Feb 14 05:50:05 firewalla systemd[24776]: docker-compose@ring-mqtt.service: Failed at step CHDIR spawning /bin/mkdir: No such file or directory`
`Feb 14 05:50:05 firewalla systemd[1]: docker-compose@ring-mqtt.service: Control process exited, code=exited status=200`
`Feb 14 05:50:05 firewalla systemd[24777]: docker-compose@ring-mqtt.service: Changing to the requested working directory failed: No such file or directory`
`Feb 14 05:50:05 firewalla systemd[24777]: docker-compose@ring-mqtt.service: Failed at step CHDIR spawning /bin/rm: No such file or directory`
`Feb 14 05:50:05 firewalla systemd[1]: docker-compose@ring-mqtt.service: Control process exited, code=exited status=200`
`Feb 14 05:50:05 firewalla systemd[1]: docker-compose@ring-mqtt.service: Failed with result 'exit-code'.`
`Feb 14 05:50:05 firewalla systemd[1]: Failed to start ring-mqtt service with docker compose.`

Here's what I get when I run `systemctl status docker-compose@ring-mqtt.service`:

`  Process: 32622 ExecStopPost=/bin/rm -rf $TMPDIR (code=exited, status=200/CHDIR)
  Process: 1350 ExecStartPre=/usr/local/bin/docker-compose rm -fv (code=exited, status=1/FAILURE)
  Process: 32621 ExecStartPre=/bin/mkdir -p $TMPDIR (code=exited, status=200/CHDIR)
`

This is my docker-compose.yml:

```
version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: "eclipse-mosquitto"
    network_mode: host
    volumes:
      - /sata-drive/docker/volumes/mosquitto/config:/mosquitto/config
      - /sata-drive/docker/volumes/mosquitto/data:/mosquitto/data
      - /sata-drive/docker/volumes//mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  ring-mqtt:
    container_name: ring-mqtt
    restart: unless-stopped
    image: "tsightler/ring-mqtt"
    depends_on:
      - mosquitto
    ports:
      - '8554:8554'
    volumes:
      - /sata-drive/docker/volumes/ring-mqtt/data:/data
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - MQTTUSER=<my_user>
      - MQTTPASSWORD=<my_pass>
      - ENABLECAMERAS=false
      - SNAPSHOTMODE=all
```
