### DISCUSSION TITLE
What could explain a publishing interval of 300 seconds instead of 30 seconds?

### DISCUSSION THREAD

**Discussion by Mincka** [tsightler/ring-mqtt#589] [Support Q&A]
From time to time, my manually configured Alarm MQTT sensor in HA becomes unavailable, often after HA reboot.
I use a manually configured alarm to add a PIN code to it.

```
  alarm_control_panel:
    - name: Alarm with PIN Code
      unique_id: XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX
      state_topic: >-
        ring/XX/alarm/YY/alarm/state
      command_topic: >-
        ring/XX/alarm/YY/alarm/command
      availability_topic: >-
        ring/XX/alarm/YY/status
      payload_available: online
      payload_not_available: offline
      code: !secret manual_alarm_code
      code_arm_required: false
      code_disarm_required: true
```

I use the HA Addon and when this happens, my "native" device (the official one, without PIN) is not offline.

I checked the addon logs and nothing suspicious.
I used MQTT Explorer to see what messages were published and I saw that messages were not published on the usual 30 seconds time interval but 5 minutes. I've waited for 20 minutes but the manually configured devices stayed offline, despite the messages every 5 minutes.

This is not a bug report because I cannot give you much info yet and I failed to get proper info before rebooting the addon.
I did not check if the discovery topics were published at all, and I did not check exactly what devices were published every 5 minutes, maybe not all of them.

The only reference to 5 minutes I found is here:
https://github.com/tsightler/ring-mqtt/blob/main/devices/base-ring-device.js#L196

I tried to reload MQTT settings and reload the HA integration but the device stayed offline.
The manually configured device came back online as soon as I rebooted the addon.
