### DISCUSSION TITLE
Motion Activated Snapshots - Previous Events 1st Frame

### DISCUSSION THREAD

**Discussion by ghost** [tsightler/ring-mqtt#610] [Support Q&A] [answered]
Hello,

Can someone provide some insight as to why my snapshots that I am sending via notification when motion is detected are only grabbing from the last event, rather than when the motion is detected? Below is the automation I have set up, and it is being used on a variety of devices that should be able to capture a **new** snapshot when the motion is detected (Video Doorbell Pro 2, Floodlight Cam Wired Pro, and Indoor Cam (Wired) [May not be compatible?]) - I have also tried using both the frontdoor entity as well as the snapshot entity and they both seem to yield the same result and the automation traces don't show any issues. Any help is greatly appreciated, thank you! 

_Edit_ - Should have included my version info and such, here it is:
Running HA via Ubunu VM on a Windows 10 Host
Home Assistant 2023.4.2
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230406.1 - latest
Ring MQTT Version: 5.2.2

```
alias: Ring - Front Door Notification
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.front_door_motion
    to: "on"
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.petersen_home_alarm
        state: armed_home
      - condition: state
        entity_id: alarm_control_panel.petersen_home_alarm
        state: armed_away
action:
  - service: camera.snapshot
    data:
      filename: /config/www/images/snapshots/front_door-latest.jpg
    target:
      entity_id: camera.front_door.snapshot
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 500
    enabled: true
  - device_id: {myDeviceID}
    domain: mobile_app
    type: notify
    message: Front Door Camera detected a person at {{ now().strftime('%I:%M %p') }}
    title: Person Detected
    data:
      attachment:
        url: >-
          https://{myURL}/local/images/snapshots/front_door-latest.jpg
      actions:
        - action: URI
          title: Open Ring App
          url: ring://dashboard
mode: single
```
