### DISCUSSION TITLE
Ring snapshot on ding?

### DISCUSSION THREAD

**Discussion by Operations8** [tsightler/ring-mqtt#708] [Support Q&A]
I would like to make a HASS automation that does this:

Take a snapshot when someone pushes the button (ding entity) 
Save picture locally.
Send myself the screenshot via Telegram (i know how to do this)

I am not use which entitiy and how to do make the ring take a snapshot on button pushed.

**Comment by tsightler** [comment]
It's not possible to take a snapshot on-demand with ring-mqtt.  ring-mqtt supports snapshot on-motion, which should provide an updated snapshot before the ding (Ring subscription required for battery/low-power doorbells) and you can just grab the current image from the snapshot camera after a doorbell press.

**Reply by Operations8** [reply]
I have a subscription. On motion is plan B then. But how do i do that in an automation? I have set the shapshot to motion already.

**Reply by tsightler** [reply]
That's really an HA question as there's nothing unique about creating an automation for a ring-mqtt provided MQTT HA camera vs any other camera type in HA.  I would suggest looking at other examples for such automations in HA.  Some users have posted examples in the massively long thread for ring-mqtt on the HA forum, for example this one:

https://community.home-assistant.io/t/ring-device-integration-via-mqtt-w-video-streaming/102105/1007?u=tsightler

Unfortunately, I can't provide more help than this.  If you have some ring-mqtt specific questions I can try to help.

**Reply by tsightler** [reply]
Just FYI, in v5.6.0 I've provided the ability to get snapshots on Ding for doorbells so perhaps this might help here.

**Reply by jellyneck84** [reply]
@tsightler great that you implemented this. One question: When getting the snapshot from mqtt, can i specify which snapshot i want to pull (motion, ding... ) or is only a tag attached to the snapshot to let the automation know which type of snapshot it is?
I want to get the snapshot which is created from camera on ding, instead of the motion snapshot.

Currently doing this:

service: camera.haustur_snapshot
data:
  filename: /config/www/kamerafoto/haustuer_snapshot.jpg
target:
  device_id: 85xxxbalalce7efxxxxx2b661blxxx8a


How can i specify to load the ding snapshot

**Reply by tsightler** [reply]
There's only a single snapshot camera, and it only has a single, current snapshot, you can't go back and get other snapshots.  There is an attribute on the snapshot which indicates if it a motion/ding/interval/on-demand so your automation should check if the attribute is ding or not and only pull it if it is a new snapshot of type ding.

**Reply by jellyneck84** [reply]
Ah ok. So either i set the snapshot mode to "Ding", which will only create a snapshot on ringing or i need to check if the attribute is DING and otherwise ignore the snapthot. Theoretically, there should always be a DING snapshot when the ring button was pressed, so condition should always be true. Theoretically, when there is a motion detected AFTER the ring, the snapshot could be overwritten..... 

Tell me if i got this right ;-) Appreciate your quick response @tsightler

**Reply by tsightler** [reply]
There could always be cases where ring-mqtt was unable to get a snapshot for whatever reason, this should not be common however, except for battery/low-power cameras with no subscription, which will basically never work.

I'm a keep-it-simple kind of person when it comes to automations.  I basically just trigger automations on snapshot updates (i.e. any time the snapshot timestamp changed), with a condition of type = "ding" and call it a day.   Whether that meets your needs or not I can't really say, but I'm just not a fan of complex automations.

**Reply by jellyneck84** [reply]
Good idea... if anyone needs the code, this works like a charm:

alias: On Ding Haustur send Telegram notification
description: ""
trigger:
  - platform: state
    entity_id:
      - camera.haustur_snapshot
    attribute: timestamp
condition:
  - condition: state
    entity_id: camera.haustur_snapshot
    attribute: type
    state: ding
action:
  - service: camera.snapshot
    data:
      filename: /config/www/kamerafoto/haustuer_snapshot.jpg
    target:
      entity_id: camera.haustur_snapshot
  - service: telegram_bot.send_photo
    data:
      authentication: digest
      file: /config/www/kamerafoto/haustuer_snapshot.jpg
      caption: Jemand ist an der Haustür
      parse_mode: markdown
      target: 123455666 (your chat ID)
mode: single

**Reply by drharis** [reply]
Appreciate this is an old thread.  I managed to install and get this working well. Regarding the screenshot capture on ding. I never got this to work. The snapshot I am getting is old ones. I also want to ask instead of using the take snapshot service. Can we not call the snapshot image link on ring-mqtt as shown below? I am guessing the the timestamp changes that means that snapshot has already been taken by the camera and available on the snapshot link, rather than asking the snapshot camera to take another snapshot? (hope it makes sense)
alias: Snapshot on Ringing the bell
description: ""
trigger:
  - platform: state
    entity_id:
      - camera.gate_bell_snapshot
    attribute: timestamp
condition:
  - condition: state
    entity_id: camera.gate_bell_snapshot
    attribute: type
    state: ding
    enabled: true
service: notify.mobile_app_honor
data:
  message: There's someone at the Gate
  data:
    image: >-
      https://xxxxxhomeassistant.co.uk{{
      states.camera.gate_bell_snapshot.attributes.entity_picture }}
mode: single

Is it this better? Having said I do not have luck in either way to get an updated snapshot on ding

**Reply by jellyneck84** [reply]
Hello @drharis . When you don't have a subscription, the camera is not creating a snapshot on ding anymore (as it's not necessary for sending the push message in ring app). Creating a snapshot on demand is not working either.

What i use:
Activate the camera live stream in the integration:

![image](https://github.com/tsightler/ring-mqtt/assets/68947111/5da832ff-7877-498b-aeb2-eceb8a28870a)

Then, add a generic camera to HomeAssistant
![image](https://github.com/tsightler/ring-mqtt/assets/68947111/6f6b50dd-af7c-4aa0-b9e7-2c0d501c826d)

Now you can use something like this to record a 2 seconds video and send it via telegram.

alias: "[ring] Send video to telegram on ding"
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.haustur_ding
    to: "on"
condition: []
action:
  - service: camera.record
    data:
      filename: /config/www/kamerafoto/haustuer_video.mp4
      duration: 2
    target:
      entity_id: camera.homeassistant
  - service: telegram_bot.send_video
    data:
      authentication: digest
      target:
        - 65xxxxxx9
        - 67xxxxxx7
      file: /config/www/kamerafoto/haustuer_video.mp4
      parse_mode: markdownv2
      caption: Jemand ist an der Haustür
mode: single

**Reply by drharis** [reply]
hi @jellyneck84 Thanks for your response. All I was looking for is a notification with snapshot of the person who rang the bell (like the ring rich notification). I did not know that the snapshot are not taken on ding if you do not have a sing subscription. I do not have one. I thought if you select snapshot on ding on the ring-mqtt integration, it would take one.  It is a bummer that the manual snapshot is not working either. Thanks for your suggestion but as explained I am not interested in a video clip, just the snapshot on the notification. I also make use of the actionable notification to open the gate if I can see who is there etc, which is much quicker than opening another app to open the gate. This is my full automation. 

alias: "Gate ring notification "
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.gate_bell_ding_mqtt
    to: "on"
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: notify.mobile_app_honor
    data:
      message: There's someone at the Gate
      data:
        clickAction: app://com.ringapp
        image: >-
          https://xxxxxhomeassistant.co.uk{{
          states.camera.gate_bell_snapshot.attributes.entity_picture }}
        actions:
          - action: OPEN_GATE
            title: Open Gate
          - action: URI
            title: Open Reolink
            uri: app://com.mcu.reolink
        sticky: true
        ttl: 0
        priority: high
  - service: browser_mod.popup
    data:
      dismissable: true
      autoclose: false
      title: Gate Camera
      size: fullscreen
      timeout: 60000
      deviceID:
        - Fire Tablet Browser
      content:
        camera_view: live
        type: picture-glance
        entities: []
        camera_image: camera.gate_stream_ring_mqtt
    enabled: true
  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: OPEN_GATE
    timeout:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
    continue_on_timeout: false
  - type: turn_on
    device_id: 734b829756bdfd079a3d4814e855e08e
    entity_id: f45d9c7357035cfa661cf61f1158b6db
    domain: switch
mode: single


I am getting the snapshot, but it is old. It is probably because, as you mentioned, snapshot are not being captured on ding

**Comment by Operations8** [comment]
> Just FYI, in v5.6.0 I've provided the ability to get snapshots on Ding for doorbells so perhaps this might help here.

Thanks for the headsup and of course for all your hard work, could you show me how to change my current automation which uses a camera when ding is detected into taking a snapshot? I am not sure how to use the entity "button.voordeur_take_snapshot" in the action part of my automation.

Current automation:

```
alias: Screenshot - Voordeur (RING DONG)
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.voordeur_ding_2
    to: "on"
condition: []
action:
  - repeat:
      until:
        - condition: or
          conditions:
            - type: is_no_motion
              condition: device
              device_id: 32496862d964d150da13963ddc0d5b77
              entity_id: bb8870e05d36e60c94a3c462a9a0c2a3
              domain: binary_sensor
            - condition: template
              value_template: "{{ repeat.index > 3 }}"
      sequence:
        - delay:
            hours: 0
            minutes: 0
            seconds: 1
            milliseconds: 0
        - service: camera.snapshot
          data:
            filename: >-
              /media/snapshots/voordeur/voordeur_{{
              now().strftime("%Y%m%d-%H%M%S") }}.jpg
          target:
            device_id: 450715b3ac1f0bbe24951a652a02f7fb
        - service: notify.telegram_bericht_nick
          data:
            message: Bezoeker voordeur
            title: Iemand aan de deur
            data:
              photo:
                - file: >-
                    /media/snapshots/voordeur/voordeur_{{
                    now().strftime("%Y%m%d-%H%M%S") }}.jpg
                  capture: Snapshoot
mode: single
```

**Reply by awharton1977** [reply]
I use something like this. 

Button press first on take snapshot - delay for these to be generated and then snapshot to disk so they can be used to send a notification to phone etc.

```
  - service: button.press
    data: {}
    target:
      entity_id:
        - button.front_door_take_snapshot
        - button.front_take_snapshot
        - button.garden_take_snapshot
        - button.side_take_snapshot
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: camera.snapshot
    data:
      filename: /config/www/front_door.jpg
    target:
      entity_id: camera.front_door_snapshot
  - service: camera.snapshot
    data:
      filename: /config/www/front.jpg
    target:
      entity_id: camera.front_snapshot
  - service: camera.snapshot
    data:
      filename: /config/www/garden.jpg
    target:
      entity_id: camera.garden_snapshot
  - service: camera.snapshot
    data:
      filename: /config/www/side.jpg
    target:
      entity_id: camera.side_snapshot
```

**Reply by tsightler** [reply]
Note that you should not need to take a manual snapshot if you have a Ring subscription, the image provided automatically by ring-mqtt will be the same one sent as part of the Ring rich notification sent to the device.

**Reply by Operations8** [reply]
I don't mind it being the same. But i want to Send the snapshot to my telegram. Easier to open quickly to have a Quick look who is at the door. Telegram way quicker than Ring app.

I do have Ring subscription.

**Reply by tsightler** [reply]
Sure, I understand that, I'm just saying that you don't have to take the manual snapshot with the button for this to work.  The on-demand snapshot button tells the camera to take yet another snapshot, which is slower than just triggering on ding and then using the snapshot that is retrieved as part of the notification.

**Reply by Operations8** [reply]
I get what you are saying. But how do i create an automation which take the automatically created image saves it locally and send it to my telegram?

**Reply by tsightler** [reply]
Does your current automation not work?  I would think it would be fine, although you could potentially wait on the next state changes on the snapshot camera vs just a random 1 second delay, which might not always be enough (Ring API is not always super fast retrieving the snapshot).

**Reply by Operations8** [reply]
My current automation doesn't use the ring snapshot, it uses a different camera to take the snapshot on the ding. I dont know how to integrate the ring snapshot.

**Reply by tsightler** [reply]
You use it like any other Home Assistant camera, exactly what you are already doing, just use the entity id of the snapshot camera.

**Reply by Operations8** [reply]
Yes but when i do that, like this:
```
alias: Ring2
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.voordeur_ding_2
    to: "on"
condition: []
action:
  - repeat:
      until:
        - condition: or
          conditions:
            - type: is_no_motion
              condition: device
              device_id: 32496862d964d150da13963ddc0d5b77
              entity_id: bb8870e05d36e60c94a3c462a9a0c2a3
              domain: binary_sensor
            - condition: template
              value_template: "{{ repeat.index > 3 }}"
      sequence:
        - delay:
            hours: 0
            minutes: 0
            seconds: 1
            milliseconds: 0
        - service: camera.snapshot
          data:
            filename: >-
              /media/snapshots/ring/voordeur_{{ now().strftime("%Y%m%d-%H%M%S")
              }}.jpg
          target:
            entity_id: camera.voordeur
        - service: notify.telegram_bericht_nick
          data:
            message: Bezoeker voordeur
            title: Iemand aan de deur
            data:
              photo:
                - file: >-
                    /media/snapshots/ring/voordeur_{{
                    now().strftime("%Y%m%d-%H%M%S") }}.jpg
                  capture: Snapshoot
mode: single
```

The snapshot is black white and not current. (Camera.voordeur is from the normal Ring integration)
