### DISCUSSION TITLE
Getting previous snapshot, how to get current one?

### DISCUSSION THREAD

**Discussion by TheFern2** [tsightler/ring-mqtt#732] [General Discussion]
I am most likely doing something wrong, I have an automation for motion, and it does work and the whole automation goes through it steps, however when it comes to saving the snapshot, it is saving the previous snapshot.

I posted a question in the HA forum I thought to post it here just in case someone knows. https://community.home-assistant.io/t/ring-mqtt-automation-with-doorbell-trouble-getting-snapshot-on-time/613999

As an example here are the last snapshots taken and saved to disk:

![image](https://github.com/tsightler/ring-mqtt/assets/10265682/5b1e5d10-884c-4125-ae5d-b127ad58aabb)

Below screenshot is from file 152317.jpg taken at 15:03:17, not file 150023, so for me clearly the automation is working because the snapshots are being taken but unsure why is grabbing the previous snapshot. Also I waited 5 or 10min and I always get the previous snapshot. Any help would greatly be appreciated.

![image](https://github.com/tsightler/ring-mqtt/assets/10265682/b0725767-b8f2-42c8-bab4-a257ec56cc26)

```
alias: Ring door motion 1
description: ""
trigger:
  - type: motion
    platform: device
    device_id: 88398fd300452f135004ae0face90004
    entity_id: 813486f548cdd5d867c90d44c6e0710e
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - type: occupied
    platform: device
    device_id: 88398fd300452f135004ae0face90004
    entity_id: 4925e1a4d8a97f32960e95af036c4e8a
    domain: binary_sensor
condition:
  - condition: time
    before: "22:00:00"
    after: "06:00:00"
action:
  - type: turn_on
    device_id: 88398fd300452f135004ae0face90004
    entity_id: 13f026ee621dc06b8a15d44e15b94dd5
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
    enabled: true
  - device_id: 88398fd300452f135004ae0face90004
    domain: button
    entity_id: 8b44cc0d43257930db8f1fa49fafe754
    type: press
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
    enabled: true
  - service: camera.snapshot
    target:
      entity_id: button.front_door_take_snapshot
    enabled: false
    data: {}
  - service: camera.snapshot
    data:
      filename: /media/camera/frontdoor/camera_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg
    target:
      device_id: 88398fd300452f135004ae0face90004
    enabled: false
  - service: camera.snapshot
    data:
      filename: /media/camera/frontdoor/camera_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg
    target:
      entity_id: camera.front_door_snapshot
    enabled: true
  - service: notify.mobile_app_sm_n960u
    data:
      message: test fernando message
  - type: turn_off
    device_id: 88398fd300452f135004ae0face90004
    entity_id: 13f026ee621dc06b8a15d44e15b94dd5
    domain: switch
mode: single

```
