### DISCUSSION TITLE
Capture Sensor that Triggered Alarm

### DISCUSSION THREAD

**Discussion by ilny89** [tsightler/ring-mqtt#877] [General Discussion]
Does anyone if I can capture the sensor that triggered my Ring alarm?

My goal is to broadcast the sensor's name that triggered the alarm on my Google Smart Speakers.

Thank you!

**Comment by tsightler** [comment]
At this time the only way to do that would be an automation that checks for the faulted sensors.  I would think that would be pretty easy with a template sensor in HA.  Obviously there would be a very small chance that the wrong sensor would somehow be detected as, theoretically, multiple sensors might be triggered by the time the automation runs, but that seems very unlikely since the state should be reflected in <1 second.

Ring is in the processes of moving to new style FCM push notifications, and these notifications include some additional metadata that might make features like this more possible in the future as I could potentially publish the text portions of the notification data directly.  We'll need to wait and see what data alarm push notifications have, but what I see with cameras is promising.  In theory it could be done today by parsing out the websocket data for the state changes, but it would require analyzing the state messages enough to fully understand them and that requires a time commitment beyond what I have today.

**Reply by ilny89** [reply]
Thank you!

**Comment by truncsphere** [comment]
I know this is an older topic, but are there any examples or some more clarification around this?

**Reply by tsightler** [reply]
Probably just ask ChatGPT or Claude to write an example automation for you, something like this (not a real example, but roughly the idea):

```
automation:
  - id: alarm_triggered_identify_sensors
    alias: "Identify faulted sensors when alarm triggers"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.mqtt_alarm
        to: "triggered"
    action:
      - variables:
          monitored_sensors:
            - binary_sensor.front_door
            - binary_sensor.back_door
            - binary_sensor.garage_door
            - binary_sensor.kitchen_window
            - binary_sensor.living_room_motion
            - binary_sensor.hallway_motion
          faulted_sensors: >
            {{ monitored_sensors | select('is_state', 'on') | list }}
          faulted_names: >
            {{ faulted_sensors | map('state_attr', 'friendly_name') | list }}
      - service: notify.mobile_app_your_phone
        data:
          title: "🚨 Alarm Triggered!"
          message: >
            {% if faulted_sensors | length > 0 %}
              Faulted sensors ({{ faulted_sensors | length }}): {{ faulted_names | join(', ') }}
            {% else %}
              Alarm triggered but no monitored sensors currently faulted.
            {% endif %}
```

Would create an message like below:

🚨 Alarm Triggered!
Faulted sensors (2): Front Door, Living Room Motion
