### ISSUE TITLE
Set to true? for retain messages

### ISSUE THREAD

**Issue by gbdavidx** [tsightler/ring-mqtt#10]
I just noticed this as someone pointed out in a home-assistant thread, if i were to set this to True, would home-assistant keep mqtt messages after a reboot?

```
mqtt:
  broker: 127.0.0.1
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 0
    retain: false
```
