### ISSUE TITLE
Cannot arm alarm via mqtt command

### ISSUE THREAD

**Issue by andreaslink-de** [tsightler/ring-mqtt#184]
I am not sure, if this is a bug or just a problem of me using it.
I am running a new **ring alarm gen. 2** and I run ring-mqtt via docker-compose in a container. The refresh token I had created was generated by using my main user login. Using _mosquitto_sub_ I see all messages and states as expected, so the overall process works.

My docker-compose file:
```
version: '3.3'
services:
  ring-mqtt:
    container_name: ring-mqtt
    hostname: ringmqtt-docker
    restart: unless-stopped
    image: tsightler/ring-mqtt
    environment:
      - RINGTOKEN=aaaaMYTOKENHEREzzzz
      - MQTTHOST=192.168.0.253
      - MQTTPORT=1883
      - MQTTRINGTOPIC=ring
      - ENABLECAMERAS=true
      - ENABLEPANIC=true
      - ENABLEMODES=true
      - ENABLEVOLUME=true
      - TZ=Europe/Berlin
    volumes:   #Local-Path:Container-Path
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./ring-mqtt:/data
```

According to the documentation I get the alarm state the same way I can set the state:

```
ring/<location_id>/alarm/<device_id>/alarm/state     <-- Alarm arming state (pending = entry delay)
                                                         disarmed/armed_home/armed_away/pending/triggered
ring/<location_id>/alarm/<device_id>/alarm/state     <-- Set alarm mode: disarm/arm_home/arm_away
```

So when monitoring I can see the state pretty well via MQTT:
`ring/MY_LOCATION_ID/alarm/MY_ALARMDEVICE_ID/alarm/state disarmed`

When I then try to activate the alarm nothing happens (I copied the values of MY_LOCATION_ID and MY_ALARMDEVICE_ID from the former status to be sure):

`mosquitto_pub -h 192.168.0.253 -t "ring/MY_LOCATION_ID/alarm/MY_ALARMDEVICE_ID/alarm/state" -m arm_home`

I would expect the alarm mode to change according to my requested type/mode.

I used the debug flag in my docker-compose file:
`DEBUG=ring-mqtt`
But I did not see anything in relation to my arm command when looking at the output while sending in the arm command via MQTT. My immediate assumption would be that the ring-mqtt did not subscribe to the set-topic itself, so no activation information are passed into the container, but I do not know, how to proof/test this.

So any advice/idea is welcome or I hope there is a trick to get this issue fixed.
