### ISSUE TITLE
Permissions Denied (non root)

### ISSUE THREAD

**Issue by aneisch** [tsightler/ring-mqtt#249]
** Describe the bug **
Since 4.8.0 with s6, the container fails to start when user is specified in docker run or docker-compose. 
 
**Debug Logs**
```
s6-overlay-preinit: fatal: unable to mkdir /var/run/s6: Permission denied
s6-overlay-preinit: fatal: unable to mkdir /var/run/s6: Permission denied
s6-overlay-preinit: fatal: unable to mkdir /var/run/s6: Permission denied
s6-overlay-preinit: fatal: unable to mkdir /var/run/s6: Permission denied
```

```
    ring-mqtt:
        container_name: ring-mqtt
        image: tsightler/ring-mqtt
        restart: 'always'
        user: '99'
        environment:
            - MQTTHOST=10.0.1.22
            - ENABLEMODES=true
            - SNAPSHOTMODE=all
            - ENABLECAMERAS=true
        volumes:
            - '/opt/ring-mqtt:/data'
```
