### ISSUE TITLE
Snapshot entity is not being created in HA

### ISSUE THREAD

**Issue by Albuca** [tsightler/ring-mqtt#272]
**Describe the problem**  
Snapshot entitles are not being created in Home Assistant.  The logs of ring-mqtt show that MQTT topics are being published, and MQTT/HA create all other entities (sensors), but no camera snapshot entity.
I can access the RTSP stream just fine (when I port forward), but getting the static snapshot is eluding me.

I notice that in the ring-mqtt, it is NOT creating a snapshot "ring-mqtt HASS config topic"

**Describe your environment**  
Everything is running in docker containers; Home Assistant, Mosquitto, ring-mqtt, etc. on Ubuntu 20.04 server

**Describe any steps you've taken to attempt to resolve the problem**  
Tried all of the snapshot settings as environmental options.  The ring app does have snapshots set to every 1 minute, but your documentation indicates that it will respect that and follow that instead.

Docker Compose:
```
# Ring-MQTT
  ring-mqtt:
    container_name: ring-mqtt
    restart: unless-stopped
    image: tsightler/ring-mqtt
    ports:
      - 8554:8554
    volumes:
      - /home/alex/docker/ring-mqtt:/data
    environment:
      - RINGTOKEN=<<Long Token>>
      - MQTTHOST=192.168.0.150
      - MQTTPORT=1883
      - MQTTUSER=<<username>
      - MQTTPASSWORD=<<password>>
      - ENABLECAMERAS=true
      - SNAPSHOT_MODE=all
    logging:
      options:
        max-size: 10m
        max-file: "3"
```

**Debug Logs**

~~ I'll send them to your email ~~
