### ISSUE TITLE
WARNING - Unhandled Promise Rejection

### ISSUE THREAD

**Issue by alvinchen1** [tsightler/ring-mqtt#351]
### Describe the bug
Update to 2022.4, and using branch DEV results in WARNING - Unhandled Promise Rejection

### Describe your environment
core-2022.4.0
supervisor-2022.03.5
Home Assistant OS 7.6

Configuration:
enable_cameras: true
snapshot_mode: all
livestream_user: {REDACTED}
livestream_pass: {REDACTED}
enable_modes: true
enable_panic: true
beam_duration: 0
disarm_code: ''
mqtt_host: <auto_detect>
mqtt_port: <auto_detect>
mqtt_user: <auto_detect>
mqtt_password: <auto_detect>
branch: dev
debug: ring-*
ring_token: ''
location_ids:
  - ''

### Describe your settings and what you've tried
Following a reboot of the entire system (Power Off/Power On), error started occurring.  All devices are unavailable.
Was able to return to branch: addon but lost Glass Break Sensors (https://github.com/tsightler/ring-mqtt/issues/327) and Ring Floodlight Pro Camera back to Unknown (https://github.com/tsightler/ring-mqtt/issues/319) but Light and Siren seem to work.
Mostly for your informational at this point.  I can wait on master/addon until you deploy your next version.

### Debug Logs

2022-04-06T21:58:04.458Z ring-mqtt WARNING - Unhandled Promise Rejection
TypeError: Cannot set properties of undefined (setting 'interval')
    at Camera.updateSnapshotMode (/app/ring-mqtt-dev/devices/camera.js:309:51)
    at Camera.init (/app/ring-mqtt-dev/devices/camera.js:194:14)
    at EventEmitter.<anonymous> (/app/ring-mqtt-dev/devices/base-ring-device.js:33:18)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.<anonymous> (/app/ring-mqtt-dev/lib/state.js:33:29)
    at EventEmitter.emit (node:events:390:28)
    at new RingPolledDevice (/app/ring-mqtt-dev/devices/base-polled-device.js:27:21)
    at new Camera (/app/ring-mqtt-dev/devices/camera.js:9:9)
    at RingMqtt.getDevice (/app/ring-mqtt-dev/lib/ring.js:264:20)
    at RingMqtt.updateRingData (/app/ring-mqtt-dev/lib/ring.js:206:45)

**Comment by alvinchen1** [comment]
Also, am totally willing to go back to Branch Dev if it will help you troubleshoot/diagnose/resolve issue as well.

**Comment by tsightler** [comment]
Thanks alvinchen1.  This was a bug that slipped in with all of the new state changes that I've been working on specifically related to cameras that operate on battery (I'm assuming you must have at least one camera that operates on battery maybe?).  This should be fixed in the dev branch now.    I'm hoping that the next version will come soon, but it's been quite a journey with the changes needed for WebRTC/Ring Edge and push notifications.  I think it's close.

**Comment by alvinchen1** [comment]
Yup, I have 1 camera with a battery state.  I went back to dev and issue is now resolved.  Break Glass sensors working, Ring Floodlight Pro camera known again.

Also slightly off topic, and FYI, but changes in 2022.4.0 to Generic Camera moving out of Yaml to UI seems to have caused a minor problem in Generic Camera setup related to still_image. 

Before 2022.4.0, my Yaml for generic camera was for example

```
camera:
  - platform: generic
    name: Back Yard Live
    still_image_url: http://homeassistant:8123{{ states.camera.back_yard_snapshot.attributes.entity_picture }}
    stream_source: rtsp://[secret]@03cabcc9-ring-mqtt:8554/909a77ff8182_live
  - platform: generic
    name: Back Yard Event
    still_image_url: http://homeassistant:8123{{ states.camera.back_yard_snapshot.attributes.entity_picture }}
    stream_source: rtsp://[secret]@03cabcc9-ring-mqtt:8554/909a77ff8182_event

```

Now with 2022.4.0, still_image has to be commented out otherwise the generic camera does not convert into UI and becomes unknown/non-functional.  Even when commented out, it took two/three reboots of core for all 8 cameras (event and live) to show up on UI.  

Looks like Home Assistant is aware of the bug.

https://github.com/home-assistant/core/issues/69461

Just wanted to share in case others having similar problems with 2022.4.0.

I've been watching your coding efforts (sorry still learning otherwise would try and be more actively contributing).  I've been right along side your journey, rooting for you, and trying to comprehend each of your commits so I can learn.  Thanks for all your efforts! Hopefully my bug reports are helpful, not burdensome.
