### ISSUE TITLE
Issues with snapshots

### ISSUE THREAD

**Issue by smarthomeaf** [tsightler/ring-mqtt#371]
### Describe the bug
A clear and concise description of the issue.  Please enter a brief summary of the issue in the title above as well.
When I create a notification using the motion sensor, the snapshots aren't updating quickly enough so they are useless. 

### Describe your environment
Please include details on your enviornment, including OS versions, platform, etc.
Home Assistant Core 2022.5.4

### Describe your settings and what you've tried
Please make sure to share you configuration settings (other than sensitive information like token, etc) and anything you have done to attempt to solve the problem to this point.
I have built the following automation to try to replicate the notifications from the ring app, however most of my notifications show no people in them because the snapshot entity is not updated before the notification is sent. I am hoping there's a way to get this to update faster, because putting in a delay would make the notifications slower which sort of defeats the purpose of having them in the first place.

I have tried setting the cameras to all, and motion for updates, and the interval is set to 10 seconds (these are all wired floodlights and doorbells pro's). You mentioned in version 5.0 that there is a way to get the info from the rich notifications within the ring app, but I didn't see any documentation on how to go about this. 

```
alias: '📱🏃🏼Notification: Outside Motion'
description: ''
trigger:
  - platform: state
    entity_id:
      - binary_sensor.backyard_camera_outside_motion
      - binary_sensor.driveway_camera_outside_motion
      - binary_sensor.front_door_camera_outside_motion
    from: 'off'
    to: 'on'
condition:
  - condition: template
    value_template: '{{ trigger.to_state.attributes.personDetected == true }}'
action:
  - service: camera.snapshot
    data:
      filename: >-
        /media/{{ trigger.entity_id.split('.')[1].replace('_outside_motion', '')
        }}.jpg
    target:
      entity_id: >-
        camera.{{ trigger.entity_id.split('.')[1].replace('_outside_motion', '')
        }}
    enabled: true
  - service: notify.mobile_app_brians_iphone
    data:
      message: >-
        There is a person at your {{ trigger.from_state.attributes.friendly_name
        }}
      title: Person Detected
      data:
        image: >-
          /media/local/{{
          trigger.entity_id.split('.')[1].replace('_outside_motion', '') }}.jpg
        push:
          thread-id: motion-notify
```

### Debug Logs
In many cases the only way to effectively troubleshoot an issue is to review the logs, without this, I'll mostly just be guessing at the problem.  Please run the script with DEBUG=ring-* enabled (note this is enabled by default for the addon and Docker versions) and collect logs.  Logs will likely contain potentially sensitive information so you probably do not want to post them publicly on Github, which I certainly understand.  Please feel free to send the logs, or a link to download them, to my personal email address, which is the same username at gmail and be sure to reference the open issue by number or link.
